- name: remove zookeeper home directory
  file:
    path: /opt/zookeeper
    state: absent

- name: create zookeeper home directory
  file:
    path: /opt/zookeeper
    state: directory

- name: create zookeeper data directory
  file:
    path: /data/zookeeper
    state: directory

- name: download and extract zookeeper
  unarchive:
    src: "https://dlcdn.apache.org/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    dest: /opt/zookeeper
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: install openjdk 17
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: true

- name: create system file for zookeeper
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
  notify:
    - systemd daemon reload
    - restart zookeeper

- name: configure zoo.cfg
  template:
    src: zoo.cfg.j2
    dest: /opt/zookeeper/conf/zoo.cfg
  notify: restart zookeeper

- name: set zookeeper_id
  set_fact:
    zookeeper_id: "{{ (ansible_hostname.split('-')[-1])|int + 1 }}"

- name: configure zookeeper server id
  copy:
    content: "{{ zookeeper_id }}"
    dest: /data/zookeeper/myid
  notify: restart zookeeper
