apiVersion: v1
kind: Service
metadata:
  name: sentry-clickhouse-0
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    statefulset.kubernetes.io/pod-name: sentry-clickhouse-0
