apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: junrui.chen@jchen.au
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - jchen.au
        dns01:
          cloudDNS:
            project: sentry-1050
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: junrui.chen@jchen.au
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsZones:
            - jchen.au
        dns01:
          cloudDNS:
            project: sentry-1050
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-jchen-au
spec:
  secretName: wildcard-jchen-au
  duration: 2160h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "jchen.au"
    - "*.jchen.au"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
